use crate::character::Character;
use crate::effect::{CCEffect, EffectTiming};
use crate::stat::StatKind;
use crate::state::{State, StateData};
use crate::utils::Position;
use serde::{Deserialize, Serialize};
use std::fmt::Debug;
use std::hash::Hash;

/// Marks the kind of an applied skill or status effect.
///
/// `Other` compares by function pointer address for `Eq` and `Hash`. Two distinct sources can
/// merge into one address if they compile to the same machine code, which is accepted here:
/// functions that behave identically are identical for this purpose.
#[warn(private_interfaces)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct EffectKindOther(*const u8);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EffectKind {
    Damage {
        coef_num: u16,
        coef_den: u16,
    },
    Heal {
        coef_num: u16,
        coef_den: u16,
    },
    Buff {
        ty: StatKind,
        duration: u16,
        scale: u16,
        amount: u32,
    },
    Debuff {
        ty: StatKind,
        duration: u16,
        scale: u16,
        amount: u32,
    },
    Move,
    CC {
        ty: CCEffect,
        duration: u16,
    },
    Other(EffectKindOther),
}

impl EffectKind {
    #[inline]
    pub fn new_other<'a>(func: fn(&Skill, State<'a>) -> State<'a>) -> Self {
        EffectKind::Other(EffectKindOther(func as *const u8))
    }
    #[inline]
    pub fn is_other(&self) -> bool {
        if let EffectKind::Other(_) = self {
            true
        } else {
            false
        }
    }
    #[inline]
    pub fn as_other<'a>(&self) -> Option<fn(&Skill, State<'a>) -> State<'a>> {
        match self {
            EffectKind::Other(ptr) => unsafe {
                if ptr.0.is_null() {
                    None
                } else {
                    std::mem::transmute(ptr)
                }
            },
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SkillEffectTarget {
    Boss { kind: EffectKind },
    Student { kind: EffectKind, count: u8 },
    Land { kind: EffectKind, region: Region },
    Oneself { kind: EffectKind },
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(tag = "shape", rename_all = "lowercase")]
pub enum Region {
    Polygon {
        /// 항상 4개를 채우고 실제로 쓰는 개수만 `count`에 적음. 남는 자리는 무시됨.
        vertex: [Position; 4],
        count: u8,
    },
    Arc {
        radius: u16,
        start_angle_degree: u16,
        end_angle_degree: u16,
    },
}
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SkillEffect {
    pub id: (u32, u8),
    pub timing: EffectTiming,
    pub targets: Vec<SkillEffectTarget>,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SkillType {
    Ex,
    Basic,
    Enhanced,
    Sub,
    NormalAttack,
    /// 전투 시작 시 걸린 채로 유지되는 보스 패시브.
    Passive,
}
use macros::dispatch_method;

/// Numeric parameters of a skill.
///
/// All three have defaults because `#[skill]` only sees the name of the params type, never its
/// fields, and so cannot tell whether a given value exists.
pub trait SkillParams {
    fn cost(&self) -> u8 {
        0
    }
    fn duration(&self) -> u16 {
        0
    }
    fn frames(&self) -> u16 {
        0
    }
}

/// For skills that carry no numbers.
impl SkillParams for () {}

/// Builds a skill from a name and its parameters.
///
/// `Params` is associated so that assembly code need not name the type. The owner is a
/// `Character` so students and bosses share one trait, at the cost of a runtime panic when the
/// variant does not match.
pub trait FromParams: Sized {
    type Params: SkillParams;

    fn new(
        name: &str,
        owner: Character<'_>,
        skill_mask_offset: usize,
        params: Self::Params,
    ) -> Self;
}

/// The mechanical half of a skill, generated by `#[skill]`.
///
/// Split from [`SkillOps`] because a trait can only be implemented in one block: with all nine
/// methods in one trait there would be nowhere to put the hand-written ones.
pub trait SkillMeta {
    fn name(&self) -> &str;
    fn owner(&self) -> Character<'_>;
    fn cost(&self) -> u8;
    fn duration(&self) -> u16;
    fn frames(&self) -> u16;
    fn skill_mask_offset(&self) -> usize;
    fn skill_type(&self) -> SkillType;
}

/// The game-logic half of a skill. Never generated.
pub trait SkillOps: SkillMeta {
    fn skill_effects(&self) -> Vec<SkillEffect>;
    fn apply<'a: 'b, 'b, 'c: 'b>(
        &self,
        caster: &'c mut StateData<'a>,
        targets: &'b mut [&'c mut StateData<'a>],
    );
}

macro_rules! define_skill {
    ($($skill_name:tt),* $(,)?) => {
        #[derive(Debug)]
        pub enum Skill {
            $($skill_name($skill_name),)*
        }

        impl SkillMeta for Skill {
            dispatch_method!(Skill, fn name(&self) -> &str, $($skill_name),*);
            dispatch_method!(Skill, fn owner(&self) -> Character<'_>, $($skill_name),*);
            dispatch_method!(Skill, fn cost(&self) -> u8, $($skill_name),*);
            dispatch_method!(Skill, fn duration(&self) -> u16, $($skill_name),*);
            dispatch_method!(Skill, fn frames(&self) -> u16, $($skill_name),*);
            dispatch_method!(Skill, fn skill_mask_offset(&self) -> usize, $($skill_name),*);
            dispatch_method!(Skill, fn skill_type(&self) -> SkillType, $($skill_name),*);
        }

        impl SkillOps for Skill {
            dispatch_method!(Skill, fn skill_effects(&self) -> Vec<SkillEffect>, $($skill_name),*);
            dispatch_method!(Skill, fn apply<'a: 'b, 'b, 'c: 'b>(&self, caster: &'c mut StateData<'a>, targets: &'b mut [&'c mut StateData<'a>]),  $($skill_name),*);
        }

        // 생성이 끝난 뒤로는 내부 데이터가 바뀌지 않음
        unsafe impl Sync for Skill {}
    };
}

// `cargo xtask` 생성물. `mod`가 아니라 `include!`인 것은 `define_skill!`이 export되지 않아
// 정의보다 뒤에서만 보이기 때문
include!("skill_defs.rs");
