use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StatKind {
    Hp,
    Atk,
    Def,
    Healing,
    Accuracy,
    Evasion,
    Crit,
    CritRes,
    CritDmg,
    CritDmgRes,
    Stability,
    StabilityRate,
    NormalAttackRange,
    SightingRange,
    CcPower,
    CcRes,
    RecoveryBoost,
    CostRecovery,
    AtkSpeed,
    MovSpeed,
    BlockRateBonus,
    DefensePiercing,
    MagCount,
    DmgDealt,
    DmgResist,
    ExSkillDmgDealt,
    ExSkillDmgResist,
    BasicsProficiency,
    HealingBoost,
    ExplosiveEffectiveness,
    PiercingEffectiveness,
    CorrosiveEffectiveness,
    MysticEffectiveness,
    SonicEffectiveness,
    BuffRetention,
    DebuffRetention,
}
